package com.rentflow.mapper;

import com.rentflow.dto.request.BulkUnitRequest;
import com.rentflow.dto.request.UnitRequest;
import com.rentflow.dto.response.UnitResponse;
import com.rentflow.entity.Unit;
import com.rentflow.entity.enums.OccupancyStatus;

import java.util.UUID;

public class UnitMapper {

    private static final String DEFAULT_STATUS = "ACTIVE";

    public static UnitResponse toDto(Unit unit) {
        return toDto(unit, null);
    }

    public static UnitResponse toDto(Unit unit, String blockName) {
        if (unit == null) {
            return null;
        }

        return UnitResponse.builder()
                .id(unit.getId())
                .propertyId(unit.getPropertyId())
                .blockId(unit.getBlockId())
                .blockName(blockName)
                .unitNumber(unit.getUnitNumber())
                .type(unit.getType())
                .floorNumber(unit.getFloorNumber())
                .bedrooms(unit.getBedrooms())
                .bathrooms(unit.getBathrooms())
                .sizeSqFt(unit.getSizeSqFt())
                .rentAmount(unit.getRentAmount())
                .depositAmount(unit.getDepositAmount())
                .occupancyStatus(unit.getOccupancyStatus())
                .furnished(unit.getFurnished())
                .waterMeterNumber(unit.getWaterMeterNumber())
                .electricityMeterNumber(unit.getElectricityMeterNumber())
                .description(unit.getDescription())
                .status(unit.getStatus())
                .build();
    }

    public static Unit toEntity(UnitRequest request, UUID propertyId) {
        if (request == null) {
            return null;
        }

        return Unit.builder()
                .propertyId(propertyId)
                .blockId(request.getBlockId())
                .unitNumber(request.getUnitNumber().trim())
                .type(request.getType())
                .floorNumber(request.getFloorNumber())
                .bedrooms(request.getBedrooms() != null ? request.getBedrooms() : 0)
                .bathrooms(request.getBathrooms() != null ? request.getBathrooms() : 0)
                .sizeSqFt(request.getSizeSqFt())
                .rentAmount(request.getRentAmount())
                .depositAmount(request.getDepositAmount())
                .occupancyStatus(OccupancyStatus.VACANT)
                .furnished(request.getFurnished() != null ? request.getFurnished() : false)
                .waterMeterNumber(request.getWaterMeterNumber())
                .electricityMeterNumber(request.getElectricityMeterNumber())
                .description(request.getDescription())
                .status(request.getStatus() != null ? request.getStatus() : DEFAULT_STATUS)
                .build();
    }

    /**
     * Builds one unit of a bulk batch. The unit number is pre-generated by the
     * service so numbering rules live in a single place.
     */
    public static Unit toEntity(BulkUnitRequest request, UUID propertyId, String unitNumber) {
        if (request == null) {
            return null;
        }

        return Unit.builder()
                .propertyId(propertyId)
                .blockId(request.getBlockId())
                .unitNumber(unitNumber)
                .type(request.getType())
                .floorNumber(request.getFloorNumber())
                .bedrooms(request.getBedrooms() != null ? request.getBedrooms() : 0)
                .bathrooms(request.getBathrooms() != null ? request.getBathrooms() : 0)
                .sizeSqFt(request.getSizeSqFt())
                .rentAmount(request.getRentAmount())
                .depositAmount(request.getDepositAmount())
                .occupancyStatus(OccupancyStatus.VACANT)
                .furnished(request.getFurnished() != null ? request.getFurnished() : false)
                .description(request.getDescription())
                .status(DEFAULT_STATUS)
                .build();
    }
}
